name: Deploy to Yandex.Cloud Object Storage

on:
  # Trigger the workflow every time you push to the `master` branch
  # Using a different branch name? Replace `master` with your branch’s name
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM dependencies
        run: pnpm i

      - name: Build application
        run: pnpm run build

      - uses: MrMeison/yc-object-storage-action@main
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
          bucketName: ${{ secrets.BUCKET }}
          sourceDir: ./dist
          clear: true
